# Generated by Django 3.0.3 on 2020-02-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20200220_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='folio',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
