# Generated by Django 3.0.3 on 2020-02-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20200220_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id',
        ),
        migrations.AddField(
            model_name='mascota',
            name='folio',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False),
        ),
    ]
